// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

// Generated by @nuxt/eslint from nuxt.config.ts. The base rules and the
// stylistic (formatting) rules both come from there.
export default withNuxt({
  ignores: ['app/components/ui/**'],
})
